#ifdef __CLING__
#pragma cling optimize(0)
#endif
void resolution_genPt()
{
//=========Macro generated from canvas: Tcan/
//=========  (Mon Jun 10 06:08:37 2024) by ROOT version 6.30/03
   TCanvas *Tcan = new TCanvas("Tcan", "",0,0,1000,800);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   Tcan->Range(-1.390244,-0.06341463,1.04878,0.4243902);
   Tcan->SetFillColor(0);
   Tcan->SetBorderMode(0);
   Tcan->SetBorderSize(2);
   Tcan->SetTickx(1);
   Tcan->SetTicky(1);
   Tcan->SetLeftMargin(0.16);
   Tcan->SetRightMargin(0.02);
   Tcan->SetTopMargin(0.05);
   Tcan->SetBottomMargin(0.13);
   Tcan->SetFrameFillStyle(0);
   Tcan->SetFrameBorderMode(0);
   Tcan->SetFrameFillStyle(0);
   Tcan->SetFrameBorderMode(0);
   
   TH1F *Num__1 = new TH1F("Num__1","Num",40,-1,1);
   Num__1->SetMinimum(0);
   Num__1->SetMaximum(0.4);
   Num__1->SetLineColor(0);
   Num__1->SetLineStyle(0);
   Num__1->SetMarkerColor(0);
   Num__1->SetMarkerStyle(20);
   Num__1->GetXaxis()->SetTitle("Resolution vs GEN p_{T}");
   Num__1->GetXaxis()->SetLabelFont(42);
   Num__1->GetXaxis()->SetLabelOffset(0.007);
   Num__1->GetXaxis()->SetLabelSize(0.03);
   Num__1->GetXaxis()->SetTitleSize(0.04);
   Num__1->GetXaxis()->SetTitleOffset(0.9);
   Num__1->GetXaxis()->SetTitleFont(42);
   Num__1->GetYaxis()->SetTitle("Fraction of Events");
   Num__1->GetYaxis()->SetLabelFont(42);
   Num__1->GetYaxis()->SetLabelOffset(0.007);
   Num__1->GetYaxis()->SetLabelSize(0.03);
   Num__1->GetYaxis()->SetTitleSize(0.04);
   Num__1->GetYaxis()->SetTitleOffset(1.25);
   Num__1->GetYaxis()->SetTitleFont(42);
   Num__1->GetZaxis()->SetLabelFont(42);
   Num__1->GetZaxis()->SetLabelOffset(0.007);
   Num__1->GetZaxis()->SetLabelSize(0.05);
   Num__1->GetZaxis()->SetTitleSize(0.06);
   Num__1->GetZaxis()->SetTitleOffset(1.1);
   Num__1->GetZaxis()->SetTitleFont(42);
   Num__1->Draw("");
   
   TH1F *Num__2 = new TH1F("Num__2","Num",40,-1,1);
   Num__2->SetBinContent(0,-nan);
   Num__2->SetBinContent(1,-nan);
   Num__2->SetBinContent(2,-nan);
   Num__2->SetBinContent(3,-nan);
   Num__2->SetBinContent(4,-nan);
   Num__2->SetBinContent(5,-nan);
   Num__2->SetBinContent(6,-nan);
   Num__2->SetBinContent(7,-nan);
   Num__2->SetBinContent(8,-nan);
   Num__2->SetBinContent(9,-nan);
   Num__2->SetBinContent(10,-nan);
   Num__2->SetBinContent(11,-nan);
   Num__2->SetBinContent(12,-nan);
   Num__2->SetBinContent(13,-nan);
   Num__2->SetBinContent(14,-nan);
   Num__2->SetBinContent(15,-nan);
   Num__2->SetBinContent(16,-nan);
   Num__2->SetBinContent(17,-nan);
   Num__2->SetBinContent(18,-nan);
   Num__2->SetBinContent(19,-nan);
   Num__2->SetBinContent(20,-nan);
   Num__2->SetBinContent(21,-nan);
   Num__2->SetBinContent(22,-nan);
   Num__2->SetBinContent(23,-nan);
   Num__2->SetBinContent(24,-nan);
   Num__2->SetBinContent(25,-nan);
   Num__2->SetBinContent(26,-nan);
   Num__2->SetBinContent(27,-nan);
   Num__2->SetBinContent(28,-nan);
   Num__2->SetBinContent(29,-nan);
   Num__2->SetBinContent(30,-nan);
   Num__2->SetBinContent(31,-nan);
   Num__2->SetBinContent(32,-nan);
   Num__2->SetBinContent(33,-nan);
   Num__2->SetBinContent(34,-nan);
   Num__2->SetBinContent(35,-nan);
   Num__2->SetBinContent(36,-nan);
   Num__2->SetBinContent(37,-nan);
   Num__2->SetBinContent(38,-nan);
   Num__2->SetBinContent(39,-nan);
   Num__2->SetBinContent(40,-nan);
   Num__2->SetBinContent(41,-nan);
   Num__2->SetBinError(0,-nan);
   Num__2->SetBinError(1,-nan);
   Num__2->SetBinError(2,-nan);
   Num__2->SetBinError(3,-nan);
   Num__2->SetBinError(4,-nan);
   Num__2->SetBinError(5,-nan);
   Num__2->SetBinError(6,-nan);
   Num__2->SetBinError(7,-nan);
   Num__2->SetBinError(8,-nan);
   Num__2->SetBinError(9,-nan);
   Num__2->SetBinError(10,-nan);
   Num__2->SetBinError(11,-nan);
   Num__2->SetBinError(12,-nan);
   Num__2->SetBinError(13,-nan);
   Num__2->SetBinError(14,-nan);
   Num__2->SetBinError(15,-nan);
   Num__2->SetBinError(16,-nan);
   Num__2->SetBinError(17,-nan);
   Num__2->SetBinError(18,-nan);
   Num__2->SetBinError(19,-nan);
   Num__2->SetBinError(20,-nan);
   Num__2->SetBinError(21,-nan);
   Num__2->SetBinError(22,-nan);
   Num__2->SetBinError(23,-nan);
   Num__2->SetBinError(24,-nan);
   Num__2->SetBinError(25,-nan);
   Num__2->SetBinError(26,-nan);
   Num__2->SetBinError(27,-nan);
   Num__2->SetBinError(28,-nan);
   Num__2->SetBinError(29,-nan);
   Num__2->SetBinError(30,-nan);
   Num__2->SetBinError(31,-nan);
   Num__2->SetBinError(32,-nan);
   Num__2->SetBinError(33,-nan);
   Num__2->SetBinError(34,-nan);
   Num__2->SetBinError(35,-nan);
   Num__2->SetBinError(36,-nan);
   Num__2->SetBinError(37,-nan);
   Num__2->SetBinError(38,-nan);
   Num__2->SetBinError(39,-nan);
   Num__2->SetBinError(40,-nan);
   Num__2->SetBinError(41,-nan);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#ff0000");
   Num__2->SetLineColor(ci);
   Num__2->SetLineStyle(0);
   Num__2->SetLineWidth(2);

   ci = TColor::GetColor("#ff0000");
   Num__2->SetMarkerColor(ci);
   Num__2->SetMarkerStyle(20);
   Num__2->SetMarkerSize(2);
   Num__2->GetXaxis()->SetLabelFont(42);
   Num__2->GetXaxis()->SetLabelOffset(0.007);
   Num__2->GetXaxis()->SetLabelSize(0.05);
   Num__2->GetXaxis()->SetTitleSize(0.06);
   Num__2->GetXaxis()->SetTitleOffset(0.9);
   Num__2->GetXaxis()->SetTitleFont(42);
   Num__2->GetYaxis()->SetLabelFont(42);
   Num__2->GetYaxis()->SetLabelOffset(0.007);
   Num__2->GetYaxis()->SetLabelSize(0.05);
   Num__2->GetYaxis()->SetTitleSize(0.06);
   Num__2->GetYaxis()->SetTitleOffset(1.25);
   Num__2->GetYaxis()->SetTitleFont(42);
   Num__2->GetZaxis()->SetLabelFont(42);
   Num__2->GetZaxis()->SetLabelOffset(0.007);
   Num__2->GetZaxis()->SetLabelSize(0.05);
   Num__2->GetZaxis()->SetTitleSize(0.06);
   Num__2->GetZaxis()->SetTitleOffset(1.1);
   Num__2->GetZaxis()->SetTitleFont(42);
   Num__2->Draw("hist same");
   
   TLegend *leg = new TLegend(0.8,0.65,0.95,0.8,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextSize(0.044);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("NULL","","h");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Num","barrel","l");

   ci = TColor::GetColor("#ff0000");
   entry->SetLineColor(ci);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   TLatex *   tex = new TLatex(0.16,0.96,"#scale[1.0]{#bf{CMS}} #scale[0.6]{#bf{Phase-2 Simulation Preliminary}}");
   tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.76,0.96,"#scale[0.8]{14 TeV, 200 PU}");
   tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetLineWidth(2);
   tex->Draw();
   Tcan->Modified();
   Tcan->SetSelected(Tcan);
}
